### ISSUE TITLE
Support for Beta layout of the site

### ISSUE THREAD

**Issue by sbobbo** [AndrewNeo/faextender-chrome#10]
In account settings, the layout of the site can be changed from classic to beta. Beta seems to have some great enhancements, but it seems that the FAExtender download button doesn't work on it. I'd love it if that got fixed.

PS: Thanks so much for the recent fix for the new version of Firefox!

**Comment by AndrewNeo** [comment]
FAE traditionally does not support the FA beta site due to manually having to inject itself into the page. Beta can change at any time and would require a lot of upkeep. Pull requests are welcome, however.
