### ISSUE TITLE
Network drives do not work for manually chosen download directory

### ISSUE THREAD

**Issue by sbobbo** [AndrewNeo/faextender-chrome#11]
When I manually set the download folder for the extension in Firefox to a network drive, it fails. It says "Error downloading".

Strangely, before I set the download folder, it succeeded in downloading to a folder on a network drive. I was hoping to stick to how i did things before and have my FA downloads default to a different directory than the browser default.

Also, It fails both when I try it via IP address and when I try with that same folder via a mapped network drive.

\\192.168.1.130\Cloud\Sync\Phone\X\X-Art\X-ArtYiff\X-ArtYiffIncoming\X-ArtYiffIncomingSort
Z:\X-Art\X-ArtYiff\X-ArtYiffIncoming\X-ArtYiffIncomingSort

**Comment by AndrewNeo** [comment]
The path has to be a subdirectory of the download folder.

https://developer.chrome.com/extensions/downloads#method-download
