### ISSUE TITLE
Submission/Journal highlighting doesn't work

### ISSUE THREAD

**Issue by momoe** [AndrewNeo/faextender-chrome#24]
I've set color parameters and chose some test artists, however nothing is being highlighted in the results. 
![image](https://user-images.githubusercontent.com/19848666/38166649-2626e898-34dc-11e8-8016-0a0d3e9ae2b8.png)
![image](https://user-images.githubusercontent.com/19848666/38166654-41f77420-34dc-11e8-8e2f-1d22ea644a00.png)

**Comment by AndrewNeo** [comment]
These only trigger on the submissions/journal pages (as evidenced by the setting title), not the gallery pages.

**Comment by momoe** [comment]
Thank you for looking into it. I have tested for case sensitivity and still has not affect.
